<?php

/**
 * Copyright © 2020 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 * Magenest_ProductFeed extension
 * NOTICE OF LICENSE
 *
 * @category Magenest
 * @package Magenest_ProductFeed
 */

namespace Magenest\ProductFeed\Block\Adminhtml\Menu\Edit\Tab;

use Magento\Backend\Block\Template\Context;
use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;
use Magento\Framework\Data\FormFactory;
use Magento\Framework\Registry;

class Templates extends Generic implements TabInterface
{
    public function __construct(
        Context $context,
        Registry $registry,
        FormFactory $formFactory,
        array $data = []
    ) {
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * Return Tab label
     *
     * @return string
     * @api
     */
    public function getTabLabel()
    {
        // TODO: Implement getTabLabel() method.
    }

    /**
     * Return Tab title
     *
     * @return string
     * @api
     */
    public function getTabTitle()
    {
        // TODO: Implement getTabTitle() method.
    }

    /**
     * Can show tab in tabs
     *
     * @return boolean
     * @api
     */
    public function canShowTab()
    {
        // TODO: Implement canShowTab() method.
    }

    /**
     * Tab is hidden
     *
     * @return boolean
     * @api
     */
    public function isHidden()
    {
        // TODO: Implement isHidden() method.
    }

    protected function _prepareLayout()
    {
        $form = $this->_formFactory->create();
        $registry = $this->_coreRegistry->registry('information');
        $fieldset = $form->addFieldset(
            'edit_form',
            [
                'legend' => __('Template Type')
            ]
        );


        $fieldset->addField(
            'type_template',
            'select',
            [
                'label' => __('Choose Type'),
                'name' => 'type_template',
                'required' => true,
                'values' => [
                    [
                        'label' => 'XML',
                        'value' => 0
                    ]
                ]
            ]
        );

        $fieldset->addField(
            'template',
            'select',
            [
                'label' => __('Choose Template'),
                'name' => 'template',
                'required' => true,
                'values' => [
                    [
                        'label' => 'Google Shopping XML',
                        'value' => 0
                    ]
                ]
            ]
        );
        $fieldset->addField(
            'template_txt',
            'textarea',
            [
                'label' => __(' Template Text'),
                'name' => 'template_txt',
                'values'
            ]
        );

        $this->setForm($form);
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}
